# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  # 에러처리
  error do |lane, exception, options|
    version = get_version_number(
      target: "Odya-iOS"
    )
    build = get_build_number 
  
    slack(
      message: "🚨 에러: #{exception}",
      success: false,
      payload: {
        "Version" => version,
        "Build" => build,
        "Build Date" => Time.new.to_s
      },
      default_payloads: [:lane]
    )
  end

  # 버전 업데이트
  def updateVersion(options)
    if options[:version]
      version = options[:version]
    else
      version = prompt(text: "Enter the version type or specific version\n(major, minor, patch or 1.0.0): ")
    end

    re = /\d+.\d+.\d+/
    versionNum = version[re, 0]

    if (versionNum)
      increment_version_number_in_xcodeproj(
        version_number: versionNum
      )
    elsif (version == 'major' || version == 'minor' || version == 'patch')
      increment_version_number_in_xcodeproj(
        bump_type: version,
        target: "Odya-iOS"
      )
    else
      UI.user_error!("[ERROR] Wrong version!")
    end
  end

  # 빌드 및 테스트 플라이트 업로드
  desc "Push a new beta build to TestFlight"
  lane :beta do |options|
    increment_build_number(
      build_number: latest_testflight_build_number + 1
    )

    updateVersion(options)

    build_app(
      scheme: "Odya-iOS",
      export_method: "app-store",
      export_options: {
	      provisioningProfiles: {
	       "com.weit.Odya-iOS" => "ODYA-AppStore-Profile-240131"
	      }
      }
    )
    
    upload_to_testflight

    version = get_version_number(
      target: "Odya-iOS"
    )
    build = get_build_number 
    slack(
      message: "✈️ Testflight 배포 성공 ✅",
      payload: {
	     "Version" => version,
       "Build" => build,
	     "Build Date" => Time.new.to_s
      },
      default_payloads: [:lane]
    )
  end
end

